package ui_views;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.util.function.Consumer;

/**
 *
 * @author Guilherme
 */
public class ChangeGreetingDialog extends JFrame {

    private Consumer<String> triggerSave;

    public ChangeGreetingDialog() {
        initComponents();
    }

    public void onChange(Consumer<String> predicate) {
        this.triggerSave = predicate;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new JLabel();
        lblSaudacao = new JLabel();
        jLabel3 = new JLabel();
        txtNewSaudacao = new JTextField();
        btnAlterarS = new JButton();
        btnCancelaS = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Saudação atual");

        lblSaudacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSaudacao.setText("Saudacao");

        jLabel3.setText("Digite uma nova saudação");

        btnAlterarS.setText("Alterar");
        btnAlterarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSActionPerformed(evt);
            }
        });

        btnCancelaS.setText("Cancelar");
        btnCancelaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaSActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(jLabel3))
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnAlterarS)
                                                        .addGap(68, 68, 68)
                                                        .addComponent(btnCancelaS))
                                                .addComponent(txtNewSaudacao)
                                                .addComponent(lblSaudacao, GroupLayout.PREFERRED_SIZE, 229, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel1)))
                                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSaudacao)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNewSaudacao, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAlterarS)
                                        .addComponent(btnCancelaS))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btnAlterarSActionPerformed(java.awt.event.ActionEvent evt) {
        this.triggerSave.accept(this.txtNewSaudacao.getText());
        this.setVisible(false);
    }

    private void btnCancelaSActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
    }

    // Variables declaration - do not modify
    private JButton btnAlterarS;
    private JButton btnCancelaS;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel lblSaudacao;
    private JTextField txtNewSaudacao;


    // End of variables declaration
}